services:
  api:
   # image: ghcr.io/danny-avila/librechat-dev-api:latest
    build:
      context: .
      dockerfile: Dockerfile.custom

    container_name: LibreChat-API
    ports:
      - 3080:3080
    depends_on:
      - rag_api
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - NODE_ENV=production
      - MONGO_URI=mongodb://host.docker.internal:27017/LibreChat
      - MEILI_HOST=http://meilisearch:7700
      - RAG_PORT=${RAG_PORT:-8000}
      - RAG_API_URL=http://rag_api:${RAG_PORT:-8000}
    volumes:
      - type: bind
        source: ./librechat.yaml
        target: /app/librechat.yaml
      - ./images:/app/client/public/images
      - ./uploads:/app/uploads
      - ./logs:/app/api/logs
      - ~/postmark-mcp:/app/api/postmark-mcp

  meilisearch:
    container_name: chat-meilisearch
    image: getmeili/meilisearch:v1.12.3
    restart: always
    env_file:
      - .env
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
    volumes:
      - ./meili_data_v1.12:/meili_data

  rag_api:
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    environment:
      - DB_HOST=host.docker.internal
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_PORT=5432
      - RAG_PORT=${RAG_PORT:-8000}
    restart: always
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  sandpack:
    image: ghcr.io/librechat-ai/codesandbox-client/bundler:latest
    ports:
      - 8080:80
    restart: always
    env_file:
      - .env
